{{- if .Values.networkpolicy.enable }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "vetes-k8s-agent.fullname" . }}
  labels:
    {{- include "vetes-k8s-agent.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      vetes.bioos.volcengine.com/type: executor
  policyTypes:
  - "Ingress"
  - "Egress"
  ingress:
    - {}
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
              - 100.96.0.96/32
{{- end }}
