apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vetes-k8s-agent.fullname" . }}
  labels:
    {{- include "vetes-k8s-agent.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "vetes-k8s-agent.fullname" . }}
  labels:
    {{- include "vetes-k8s-agent.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - "*"
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
      - persistentvolumeclaims
      - persistentvolumes
    verbs:
      - create
      - delete
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - watch
      - get
      - delete
      - deletecollection
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - create
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vetes-k8s-agent.fullname" . }}
  labels:
    {{- include "vetes-k8s-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vetes-k8s-agent.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "vetes-k8s-agent.fullname" . }}
    namespace: {{ .Release.Namespace }}
